# Generated by Django 5.0.6 on 2024-06-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0004_std'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='std',
            name='id',
        ),
        migrations.AlterField(
            model_name='std',
            name='roll',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
