# Generated by Django 5.0.6 on 2024-06-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0005_remove_std_id_alter_std_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='std',
            name='year',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
